openapi: "3.0.0"
info:
  title: Simple API overview - sourced from https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/api-with-examples.yaml
  version: 2.0.0
paths:
  /example:
    get:
      summary: doesn't do much
      responses:
        '200':
          description: |-
            200 response
